import type { IssueFamily } from "@/core/domain/types";

// Keyword taxonomy for deterministic issue family classification.
// Rules: prefer functional system over condition word.
// Order matters — first match wins (most specific first).

export interface TaxonomyRule {
  family: IssueFamily;
  keywords: string[];
}

export const TAXONOMY: TaxonomyRule[] = [
  // Safety-critical systems first (higher priority)
  {
    family: "Brakes",
    keywords: [
      "brake",
      "braking",
      "abs",
      "anti-lock",
      "caliper",
      "calliper",
      "brake disc",
      "brake drum",
      "brake pad",
      "brake shoe",
      "brake pipe",
      "brake hose",
      "brake fluid",
      "handbrake",
      "parking brake",
      "brake light",
      "stop light",
      "brake binding",
      "brake pull",
    ],
  },
  {
    family: "Steering",
    keywords: [
      "steering",
      "steering rack",
      "steering column",
      "steering wheel",
      "track rod",
      "tie rod",
      "power steering",
      "steering gearbox",
      "steering play",
      "steering fluid",
    ],
  },
  {
    family: "Suspension",
    keywords: [
      "suspension",
      "shock absorber",
      "damper",
      "spring",
      "coil spring",
      "anti-roll bar",
      "drop link",
      "wishbone",
      "control arm",
      "ball joint",
      "bush",
      "bushing",
      "strut",
      "subframe",
      "wheel bearing",
      "hub bearing",
      "cv joint",
      "cv boot",
      "driveshaft",
      "drive shaft",
    ],
  },
  {
    family: "Tyres/Wheels",
    keywords: [
      "tyre",
      "tire",
      "tread",
      "tread depth",
      "tread limit",
      "wheel",
      "rim",
      "alloy",
      "spare wheel",
      "tyre pressure",
      "tyre sidewall",
      "puncture",
      "nail in tyre",
      "cut in tyre",
      "bulge",
    ],
  },
  {
    family: "Seat belts/Airbags/SRS",
    keywords: [
      "seat belt",
      "seatbelt",
      "safety belt",
      "airbag",
      "air bag",
      "srs",
      "supplemental restraint",
      "restraint",
      "child seat",
      "isofix",
    ],
  },
  {
    family: "Structure/Corrosion",
    keywords: [
      "chassis",
      "subframe corroded",
      "floor corroded",
      "sill",
      "body corroded",
      "structural corrosion",
      "corrosion",
      "corroded",
      "rust",
      "rusted",
      "perforated",
      "perforation",
      "floor pan",
      "crossmember",
      "inner wing",
    ],
  },
  {
    family: "Engine management/MIL",
    keywords: [
      "engine management",
      "engine warning",
      "mil",
      "malfunction indicator",
      "eml",
      "check engine",
      "engine light",
      "dpf",
      "diesel particulate",
      "lambda",
      "oxygen sensor",
      "catalyst",
      "catalytic converter",
    ],
  },
  {
    family: "Exhaust/Emissions",
    keywords: [
      "exhaust",
      "emission",
      "co level",
      "hc level",
      "smoke",
      "blowing",
      "manifold",
      "silencer",
      "downpipe",
      "tailpipe",
    ],
  },
  {
    family: "Visibility/Windscreen/Wipers",
    keywords: [
      "windscreen",
      "wiper",
      "washer",
      "screen wash",
      "mirror",
      "rear view",
      "rear window",
      "demister",
      "visibility",
      "chip",
      "crack",
      "stone chip",
    ],
  },
  {
    family: "Lighting/Electrics",
    keywords: [
      "lamp",
      "light",
      "headlight",
      "headlamp",
      "fog lamp",
      "indicator",
      "turn signal",
      "reverse light",
      "hazard",
      "number plate light",
      "registration plate lamp",
      "bulb",
      "horn",
      "battery",
      "fuse",
      "wiring",
    ],
  },
  {
    family: "Fluid leaks",
    keywords: [
      "leak",
      "leaking",
      "oil leak",
      "coolant leak",
      "fluid",
      "dripping",
      "seeping",
    ],
  },
];

// Fallback — used only when no keyword matches
export const FALLBACK_FAMILY: IssueFamily = "Other";
